<?php

namespace Base\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatusCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusCodeRepository extends EntityRepository
{

	public function getStatusCodes(){

		$qb = $this->createQueryBuilder('sc')
		       ->orderBy('sc.id', 'asc')
		       ->getQuery();

		return $qb->getArrayResult();
	}

}
