<?php

namespace Base\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TurbineStatusCode_2012Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurbineStatusCode_2012Repository extends EntityRepository
{
}
