<?php

namespace Base\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TurbineStatusCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurbineStatusCodeRepository extends EntityRepository
{
	public function getStatusCodeTurbine($dateBegin, $dateEnd, $arrayId){

		// $rsm = new ResultSetMapping();
		// $rsm->addEntityResult('BaseCoreBundle:StatusCode', 'sc');
		// $rsm->addFieldResult('sc', 'sc_id', 'id');
		// $rsm->addFieldResult('wf', 'wf_name', 'name');
		// $rsm->addFieldResult('wf', 'wf_alias', 'alias');
		// $rsm->addJoinedEntityResult('BaseCoreBundle:TurbineStatusCode' , 'tsc', 'sc', 'statusCode');
		// $rsm->addFieldResult('t', 't_id', 'id');
		// $rsm->addFieldResult('t', 't_name', 'name');
		// $rsm->addFieldResult('t', 't_alias', 'alias');

		// $sql = 'SELECT "wf"."id" as wf_id,
		// 			   "wf"."name" as wf_name,
		// 			   "wf"."alias" as wf_alias,
		// 			   "t"."id" as t_id,
		// 			   "t"."name" as t_name,
		// 			   "t"."alias" as t_alias
  // 				FROM "maiaeolis"."WindFarm" wf
  // 				INNER JOIN "maiaeolis"."Turbine" t
  // 				ON "wf"."id" = "t"."windfarmid"';

  // 		$qb = $this->_em->createNativeQuery($sql, $rsm);

		// return $qb->getArrayResult();

		$qb = $this->createQueryBuilder('tsc')
		       ->where('tsc.statusCode IN ' . $arrayId)
		       ->orderBy('tsc.statusCode', 'asc')
		       ->getQuery();

		return $qb->getResult();
	}
}
