<?php

namespace Base\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TurbineStatusCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurbineStatusCode_2015Repository extends EntityRepository
{
	public function getStatusCodeTurbine($paramRequest){

		// conversion des dates au format spécifique à postgres (timestamp without timezone)
		$dateBegin = $paramRequest[0]->format('Y-m-d H:i:s.u');
		$dateEnd = $paramRequest[1]->format('Y-m-d H:i:s.u');
		$arrayId = $paramRequest[2];

		$qb = $this->createQueryBuilder('tsct')
		       	   // ->select('tsc', 't', 'sc')
		       	   ->select('tsc')
		       	   ->from("BaseCoreBundle:TurbineStatusCode", 'tsc')
		    	   // ->leftJoin("tsc.turbine", "t")
		    	   // ->leftJoin("tsc.statusCode", "sc")
		    	   ->where('tsc.timestamp >= \'' . $dateBegin .'\'')
		    	   ->where('tsc.timestamp <= \'' . $dateEnd .'\'')
		    	   // ->andwhere('sc.id IN ' . $arrayId)
				   // ->orderBy("tsc.timestamp, t.name, sc.id")
				   ->orderBy("tsc.timestamp")
		    	   ->getQuery();

		return $qb->getResult();
	}
}