<?php

namespace Base\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TurbineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurbineRepository extends EntityRepository
{
	public function getTurbinesCheck(){

		$tabTurbine = array();

		return $tabTurbine;
	}

	public function getAllTurbines(){
		
		$qb = $this->_em->createQueryBuilder('t')
				   ->select('t')
				   ->from("BaseCoreBundle:Turbine", 't')
				   ->orderBy("t.windFarm, t.numInWindFarm");

		return $qb;
	}
}
