<?php

namespace Base\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WindFarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WindFarmRepository extends EntityRepository
{
	public function getWindFarmsAndTurbines(){

		// $qb = $this->createQueryBuilder('wft')
		// 		   ->leftJoin('t.Turbine')
		// 		   ->addSelect('t')
		// 		   ->getQuery();

		// return $qb->getResult();
	}
}
